version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7

  - package-ecosystem: "bundler"
    directory: "/ruby"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7

  - package-ecosystem: "npm"
    directory: "/javascript"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7

# Update this date to re-trigger Dependabot
# last-reset: 2026-03-26T17:27:13

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "DAT-15011 (gha) "
    cooldown:
      default-days: 7
